# Generated by Django 3.1.3 on 2020-11-27 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grup', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duyuru', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='grup_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='grup.grup'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='kullanici_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='baslik',
            field=models.CharField(max_length=150, verbose_name='başlık'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='icerik',
            field=models.TextField(verbose_name='duyuru içeriği'),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
