# Generated by Django 3.1.3 on 2021-01-01 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20210101_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='grup_id',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='kullanici_id',
        ),
        migrations.AlterField(
            model_name='forum',
            name='tarih',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 1, 21, 59, 26, 460294)),
        ),
    ]
