# Generated by Django 3.1.3 on 2021-01-01 19:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grup', '0001_initial'),
        ('forum', '0008_auto_20210101_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='grup_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='grup.grup'),
        ),
        migrations.AddField(
            model_name='forum',
            name='kullanici_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='tarih',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 1, 22, 0, 31, 27313)),
        ),
    ]
