# Generated by Django 3.1.3 on 2021-01-03 13:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0016_auto_20210102_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='tarih',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 3, 16, 8, 24, 395089)),
        ),
        migrations.CreateModel(
            name='cevap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesaj', models.TextField(verbose_name='mesaj')),
                ('cevap_tarih', models.DateTimeField(auto_now_add=True)),
                ('cevap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='forum.forum', verbose_name='cevap')),
                ('cevap_kullanici', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
