# Generated by Django 3.1.3 on 2021-01-02 11:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='galeri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='ad')),
                ('yol', models.FileField(blank=True, null=True, upload_to='', verbose_name='Fotoğraf ekleyin')),
                ('tarih', models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 14, 55, 52, 147194))),
                ('grup_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='grup.grup')),
                ('kullanici_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
